Repository DrugCoding/SH_company_pjt, pull requests merged in 2023-03, with the labels that each got.

#2 feat : Notice 페이지 구현
  notices/forms.py
  notices/models.py
  notices/templates/notices/detail.html
  notices/templates/notices/form.html
  notices/templates/notices/index.html
  notices/templates/notices/search.html
  notices/urls.py
  notices/views.py
Labels: feature, BE

#3 feat: get_bootstrap cdn 설정
  companies/templates/companies/index.html
  templates/base.html
Labels: FE

#4 Sk 02
  companies/templates/companies/index.html
  templates/base.html
Labels: FE

#5 fix : 검색 기능 오류 수정
  notices/templates/notices/detail.html
  notices/templates/notices/index.html
  notices/views.py
Labels: BE, fix

#9 feat : Notice 조회수 구현
  notices/templates/notices/detail.html
  notices/views.py
Labels: feature, BE

#12 chore: nav 코드 수정
  companies/templates/companies/index.html
  templates/base.html
Labels: chore, FE

#13 feat : notice 이미지 기능 구현
  SH_company_pjt/settings.py
  SH_company_pjt/urls.py
  notices/admin.py
  notices/forms.py
  notices/models.py
  notices/templates/notices/detail.html
  notices/templates/notices/form.html
  notices/views.py
Labels: feature, BE

#14 feat: banner 완성, static 해결해야합니다.
  companies/templates/companies/index.html
  templates/base.html
Labels: feature, FE

#15 feat : notices 삭제 기능 구현 및 수정-삭제 관리자만 보여지게 수정
  equipments/forms.py
  equipments/models.py
  equipments/templates/equipments/form.html
  equipments/templates/equipments/index.html
  equipments/urls.py
  equipments/views.py
  notices/forms.py
  notices/templates/notices/detail.html
  notices/urls.py
  notices/views.py
Labels: chore, feature, BE

#16 bug : notice 검색 후 detail 페이지 클릭했을 때 링크 오류
  equipments/templates/equipments/form.html
  equipments/views.py
  notices/templates/notices/detail.html
  notices/templates/notices/form.html
  notices/templates/notices/index.html
  notices/templates/notices/search.html
Labels: bug, chore, BE

#17 chore : nav bar 코드 수정
  equipments/templates/equipments/detail.html
  equipments/templates/equipments/form.html
  equipments/templates/equipments/search.html
  templates/base.html
Labels: chore, FE

#18 feat : equipment 구현 중
  equipments/templates/equipments/detail.html
  equipments/templates/equipments/form.html
  equipments/templates/equipments/index.html
  equipments/templates/equipments/search.html
  equipments/urls.py
  equipments/views.py
  notices/templates/notices/detail.html
  notices/templates/notices/form.html
  notices/templates/notices/index.html
  notices/views.py
Labels: feature, BE

#20 feature: 글자 애니메이션 기능 추가
  companies/templates/companies/index.html
  templates/base.html
Labels: feature, FE

#21 bug : 카카오맵 api로 지도 구현 - env파일에 key 숨기면서 지도 안 보임
  .gitignore
  SH_company_pjt/settings.py
  notices/templates/notices/index.html
  notices/views.py
Labels: bug, BE

#22 FE: notice banner 완성
  companies/templates/companies/index.html
  static/images/notice_ttl.png
  templates/base.html
Labels: FE

#23 FE: 시공사례, 시공분야 틀 완성
  companies/templates/companies/index.html
  templates/base.html
Labels: FE

#24 chore: card margin left 값 변경
  companies/templates/companies/index.html
Labels: chore, FE

#26 chore: performances 에러 수정
  performances/templates/performances/create.html
  performances/templates/performances/detail.html
  performances/templates/performances/index.html
  performances/views.py
Labels: chore, BE, fix

#27 fix: 숨은 게시글 style:margin-top으로 찾아냄
  performances/forms.py
  performances/templates/performances/detail.html
  performances/templates/performances/index.html
  performances/views.py
Labels: chore, BE, fix

#28 chore : 장비운영 이미지 추가 위해 multipart 코드 추가
  SH_company_pjt/settings.py
  equipments/models.py
  equipments/templates/equipments/form.html
  notices/templates/notices/index.html
  notices/views.py
Labels: chore, BE

#29 chore: 관리자 입장에서 보기편하게 수정(글 수정/삭제)
  performances/templates/performances/create.html
  performances/templates/performances/detail.html
  performances/templates/performances/index.html
Labels: chore, BE

#30 chore : 카카오 지도 구현 come 페이지로 옮김
  SH_company_pjt/urls.py
  companies/templates/companies/come.html
  notices/templates/notices/index.html
Labels: chore, BE

#31 chore : form 라벨 설정
  equipments/forms.py
  equipments/templates/equipments/form.html
  notices/templates/notices/form.html
Labels: chore, BE
