Repository DrugCoding/SH_company_pjt, pull requests merged in 2023-04, with the labels that each got.

#33 chore: 공지사항 글자 추가
  companies/templates/companies/index.html
Labels: chore, FE

#34 chore: 시공사례, 시공분야 메인페이지 수정
  companies/templates/companies/index.html
Labels: chore, FE

#36 chore: footer 코드 지우기, 다른 코드 위치 수정
  companies/templates/companies/come.html
  companies/templates/companies/index.html
Labels: chore, FE

#37 feature: 메뉴 왼쪽, 오른쪽 배치완료
  companies/templates/companies/greeting.html
  static/CSS/base.css
Labels: feature, FE

#38 fix: 오류 수정
  companies/templates/companies/index.html
Labels: FE, fix

#39 fix: performances paginator 작동
  constructions/models.py
  constructions/templates/constructions/create.html
  constructions/templates/constructions/index.html
  constructions/urls.py
  constructions/views.py
  performances/templates/performances/index.html
  performances/views.py
Labels: chore, feature, BE, fix

#40 chore: 회사 소개 수정
  companies/templates/companies/greeting.html
  companies/templates/companies/index.html
  companies/templates/companies/patent.html
  templates/base.html
Labels: chore, FE

#41 feature: 특허및인증페이지
  companies/templates/companies/patent.html
  static/images/특허등록증.PNG
Labels: feature, FE

#42 feature: 오시는 길
  companies/templates/companies/come.html
Labels: feature, FE

#43 feature: 회사연혁 페이지 틀 넣기
  companies/templates/companies/come.html
  companies/templates/companies/greeting.html
  companies/templates/companies/history.html
  companies/templates/companies/index.html
  templates/base.html
Labels: feature, FE

#44 feat: base.html 등 맵핑
  companies/templates/companies/index.html
  constructions/models.py
  constructions/templates/constructions/index.html
  performances/templates/performances/index.html
  templates/base.html
Labels: chore, feature, BE

#46 fix : 공지사항 게시글 번호 인덱싱 수정
  equipments/templates/equipments/detail.html
  equipments/templates/equipments/form.html
  equipments/templates/equipments/index.html
  equipments/templates/equipments/search.html
  notices/templates/notices/detail.html
  notices/templates/notices/form.html
  notices/templates/notices/index.html
  notices/templatetags/__init__.py
  notices/templatetags/notice_filter.py
  notices/views.py
Labels: BE, fix

#47 feat : equipments 인덱스, 검색결과 페이지
  companies/templates/companies/come.html
  constructions/models.py
  constructions/urls.py
  equipments/templates/equipments/detail.html
  equipments/templates/equipments/index.html
  equipments/templates/equipments/search.html
  notices/templates/notices/index.html
Labels: feature, BE

#48 chore : equipments 검색, 페이지네이션 삭제 & 버튼 디자인 수정
  companies/templates/companies/come.html
  equipments/templates/equipments/detail.html
  equipments/templates/equipments/form.html
  equipments/templates/equipments/index.html
  equipments/urls.py
  equipments/views.py
  notices/templates/notices/detail.html
  notices/templates/notices/form.html
  notices/templates/notices/index.html
  notices/templates/notices/search.html
Labels: chore, FE

#49 feat : equipments 게시글 안에 이미지 삽입 구현
  equipments/forms.py
  equipments/models.py
  equipments/templates/equipments/detail.html
  equipments/templates/equipments/form.html
  equipments/views.py
Labels: feature, BE

#50 chore: 회사소개 페이지 완성
  companies/templates/companies/greeting.html
  companies/templates/companies/history.html
Labels: chore, FE

#51 chore: 회사연혁 페이지 완성
  companies/templates/companies/history.html
Labels: chore, FE

#52 feature: 시공분야 페이지 완성
  companies/templates/companies/come.html
  companies/templates/companies/greeting.html
  constructions/templates/constructions/index.html
  static/images/시공분야 사진.PNG
  templates/base.html
Labels: feature, FE

#53 feat:constructions app 구현(category 구현중)
  constructions/admin.py
  constructions/forms.py
  constructions/models.py
  constructions/templates/constructions/create.html
  constructions/templates/constructions/detail.html
  constructions/templates/constructions/index.html
  constructions/urls.py
  constructions/views.py
Labels: feature, BE

#54 chore:constructions app index 사진, 매핑
  constructions/templates/constructions/index.html
Labels: chore, BE, fix

#55 fix:constuctions model 수정 공사여부추가
  constructions/forms.py
  constructions/models.py
  constructions/templates/constructions/index.html
Labels: feature, BE, fix
