Repository DrugCoding/SH_company_pjt, pull requests merged in 2023-05, with the labels that each got.

#56 FE: 프론트엔드 중간점검
  companies/templates/companies/greeting.html
  companies/templates/companies/patent.html
  constructions/templates/constructions/index.html
Labels: FE

#57 chore : 장비운영 디테일 페이지 완성 & 시공분야-실적 관리자만 글쓰기 작성 버튼 보이게 수정
  constructions/templates/constructions/index.html
  equipments/templates/equipments/detail.html
  performances/templates/performances/index.html
Labels: chore, BE, FE

#58 chore: position:relative, z-index: ; 값 설정 및 css 수정
  companies/templates/companies/greeting.html
  companies/templates/companies/history.html
Labels: chore, FE

#59 chore: history.html 완료
  companies/templates/companies/history.html
Labels: chore, FE
